### ISSUE TITLE
"false == true" ERROR

### ISSUE THREAD

**Issue by jhm-ciberman** [vector-of-bool/vscode-gitflow#19]
I have an existing repository with `master` and `develop` branches and executed the command "Gitflow init" from the provided extension commands with all the default parameters and the following VSCode message appeared:  (At the top of the screen)
```
"[ERROR] false == true" (close)
```

**Comment by greggbjensen** [comment]
I have seen this many times now that Workspaces has been introduced in VS Code.

**Comment by vector-of-bool** [comment]
This was fixed in PR #18, but I didn't push out the fix until just now. Sorry for the delay. Tell me if this persists!
