### ISSUE TITLE
vscode 1.5  It doesn't work

### ISSUE THREAD

**Issue by bfgh2678** [vector-of-bool/vscode-gitflow#4]
Cannot create gitflow

**Comment by vector-of-bool** [comment]
Hmm... It seems there is something going wrong. I'll look into it.

**Comment by vector-of-bool** [comment]
Sorry for the delay... I can't seem to reproduce the issue... What are you seeing when you try to initialize your repo?

**Comment by vector-of-bool** [comment]
First, can you update to 0.1.0 and see if the behavior changes at all?

**Comment by bfgh2678** [comment]
Thank you

**Comment by vector-of-bool** [comment]
All good? If it is fixed to your satisfaction please close this issue, thanks!
