### ISSUE TITLE
Error : spawn git ENOENT

### ISSUE THREAD

**Issue by noontz** [vector-of-bool/vscode-gitflow#6]
- gitflow 0.1.0
- Code version 1.6.1
- win 10 64 PATH variable : C:\Program Files\Git\cmd\git.exe
- git 2.10.0 64

Error id thrown on all gitflow commands

Tried on empty folder with new repo
Tried on Folder with repo initialized from SmartGit

**Comment by ajsb85** [comment]
![image](https://cloud.githubusercontent.com/assets/663460/22060552/8a0198cc-dd71-11e6-8842-affa3a06ef81.png)

**Comment by vector-of-bool** [comment]
Sorry to leave this one for a while. Could I see some console output regarding the failing command? Also may be useful to see the output from `where git`, when run from a regular command line.

**Comment by ajsb85** [comment]
Relative to #10

**Comment by vector-of-bool** [comment]
After a long time of being unsure of a fix, a PR from d-schiffner has probably fixed this issue. Go out and give it a try!

**Comment by vector-of-bool** [comment]
Is anyone still experiencing this issue?
