### ISSUE TITLE
Differently named development branch not respected

### ISSUE THREAD

**Issue by jitcoder** [vector-of-bool/vscode-gitflow#7]
### Steps to reproduce
1. Init new repo
2. Create a development branch called "development" rather than "develop"
3. gitflow initialize using command palette
4. Choose master for release branch
5. Choose "development" for development branch
6. Attempt to start a new feature using command palette.

A message will pop up saying "git" returned status 128

_Please note I installed the gitflow extension for git, not sure if that was required._

Developer Tools dump:
```
extensionHost.ts:255[Extension Host] [gitflow] Execute git checkout -b feature/how-are-you develop
extensionHost.ts:255[Extension Host] [gitflow] Command "git" returned code 128: fatal: Cannot update paths and switch to branch 'feature/how-are-you' at the same time.
Did you intend to checkout 'develop' which can not be resolved as commit?

shell.ts:440"git" returned status 128e.onUnexpectedError @ shell.ts:440
winjs.base.js:45WARNING: Promise with no error callback:80
```

I see that it is still targeting "develop" rather than "development" which is what I chose to name my development branch during the initialization process.

`vscode: Version 1.7.2 (1.7.2)`

**Comment by vector-of-bool** [comment]
should be fixed in 1.0
