### ISSUE TITLE
Hotfix finish configuration

### ISSUE THREAD

**Issue by adrianofoschi** [vector-of-bool/vscode-gitflow#9]
Hi, I closed an Hotfix and it removes the remote branch. Is there way to configure plugin to preserve ALWAYS remote branches?

Thanks you

**Comment by jitcoder** [comment]
I agree that the option to delete as well as merge on finish should be configurable.
I'll see if I have the time to create a PR for this if project owner agrees with the feature request.

**Comment by vector-of-bool** [comment]
That's a pretty reasonable configuration option. I'd happily accept any PRs regarding this.

**Comment by vector-of-bool** [comment]
Should have some new config options in the 1.0 release. If you want any more additional options, I'll happily add them! Just open a new ticket or PR. Thanks for the suggestions!
